"""reset

Revision ID: 31f320fe23d1
Revises: 
Create Date: 2019-03-22 13:37:56.636460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f320fe23d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('demoLab', sa.String(length=64), nullable=True),
    sa.Column('demoTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('student',
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('cits3403', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('project')
    # ### end Alembic commands ###
