"""initial set-up

Revision ID: cd39745ce59d
Revises: 
Create Date: 2019-04-07 13:22:49.986464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd39745ce59d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('lab', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lab_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.lab_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('prefered_name', sa.String(length=64), nullable=True),
    sa.Column('cits3403', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('projects')
    op.drop_table('labs')
    # ### end Alembic commands ###
