"""user tokens

Revision ID: 9474f3dc4cf4
Revises: 79710eceaa21
Create Date: 2019-05-07 14:33:23.100382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9474f3dc4cf4'
down_revision = '79710eceaa21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('students', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_students_token'), 'students', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_token'), table_name='students')
    op.drop_column('students', 'token_expiration')
    op.drop_column('students', 'token')
    # ### end Alembic commands ###
