"""empty message

Revision ID: e6abe78cadc9
Revises: f481ab58feae
Create Date: 2019-05-19 22:04:17.576108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6abe78cadc9'
down_revision = 'f481ab58feae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('students', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_students_token'), 'students', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_token'), table_name='students')
    op.drop_column('students', 'token_expiration')
    op.drop_column('students', 'token')
    # ### end Alembic commands ###
